apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    name: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: react-app
  template:
    metadata:
      name: react-app
      labels:
        name: react-app
    spec:
      containers:
        - name: react-app
          image: hisbu/reactapp-test:tagVersion
          ports: 
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    name: react-app
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30010
    
    